---
title: "Q15 - First Year Exam"
author: "Meg Robinson PID: A59010583"
date: "2022-07-17"
output: pdf_document
---

# Load the data and packages
```{r}
df <- read.csv("covid19_variants.csv")
library(ggplot2)
library(dplyr)
library(lubridate)
```


Look at data
```{r}
head(df)
```
# Format Data

Remove 'Total' and 'Other' variants since these aren't in the plot given to us

```{r}
df <- df[!df$variant_name %in% c("Other", "Total"), ]
head(df)
```

Change the date to a 'date' variable rather than a 'character' variable using the 'lubridate' package

```{r}
# observe column variable in wrong format
class(df$date)
df$date[1]
```

```{r}
# fix above, make new column and add to df


df$new_date <- mdy(df$date)
head(df)
```

# Plot Data
```{r}
ggplot(df, aes(new_date,percentage)) +
# group by variant (hence excluding total and other)
  geom_line(aes(color = variant_name)) + 
# set theme
  theme_classic() + 
# now, format axes
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") + 
# add axes titles
  ylab("Percentage of sequenced specimens") +
  xlab("Date") +
# make x axis readable (rotate), remove legend title
  theme(axis.text.x = element_text(angle = 55,
                                   hjust = 1),
        legend.position = "right",
        legend.title = element_blank()) +
# title plot
  ggtitle("Covid-19 Variants in California") + 
# add caption to include website where data was found
  labs(caption = "Data Source: <https://data.chhs.ca.gov/dataset/covid-19-variant-data>")
```

